### ISSUE TITLE
How is \notaccent supposed to work?

### ISSUE THREAD

**Issue by davidmjones** [AmerMathSoc/mathjax-unicode-math#6]

**Comment by pkra** [comment]
After our further discussion, do we close this again? It seems MathJax's behavior is suitable.

**Comment by davidmjones** [comment]
In unicode-math, \notaccent is the fallback for \not when there are no pre-defined composite characters available, at which point the engine just tries to overlay U+0338 on top of the argument.  Since this is already built into MathJax's implementation of \not, aliasing \notaccent to \not would appear to be the correct solution.
